{% set name = "hpp-fcl" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ name }}/releases/download/v{{ version }}/hpp-fcl-{{ version }}.tar.gz
  sha256: d7dbd7ede3613bf3e499466a114d1f74ef6ed95d3901b2d59ea14aa17f303416

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - eigen
    - boost
    - python
    - eigenpy
    - assimp
    - octomap
  run:
    - assimp
    - octomap
    - boost
    - python
    - eigenpy

test:
  requires:
    - pkg-config
  imports:
    - hppfcl
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/humanoid-path-planner/hpp-fcl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An extension of the Flexible Collision Library
  dev_url: https://github.com/humanoid-path-planner/hpp-fcl

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
