travis:
  secure:
    BINSTAR_TOKEN: B7YMjPeTUpqyWibWYwQaloeodxhyTe2qMb5WrwDLUtL31YAM19s8PRwEeaIwIOjnlPvw5kWCofa6rZMNLsYZYTpDuCfzmaB9zGQhULrP1O5cMoHboEbgPxxrKgqZn4w5N4SFRdgC9D8Kh8nVpNDnYyAdpUhcTkzhIELlafAKzElQc2j1Sg0L+dDyDbzmVesWf+xvCoy4JAPAUpBlFanjiOhkosK2ZAVBaLLyqrSfCkCcs8ABf4gEy/W+Z/VkaaKGYRT2nTq3qnGRdWichj4/P8Lhy8iOD2LWzmwwUiSskE22lQlOA69Euk8HWny3duAj7jBCyhlNUFiNvUNCLtInS35iI0zZB7rDw/BrWYLJctA3W0bX4wves+m9jRSHY8afQ5knVjPQKYKX7s3h/NPCAEdHtLtneagDNCk4Fs9hden2QZhZNSD7NKJUxmnSgHG5Tjt0cMdmClJMHX9Zxr51gS81HWHmkyJBKZ8Vxy3LZQTKuJkg88SknoGS7Kd1NK+1tsGb6+MkeblkrIFM2Jll7MDxJBNm3wvG2zBKszqfX2SEmuYtH9S9M17VHXKv0MwK8j7swqgydonxDyb46l4i9HU68y3BJoCsCgONJAFtjQwRYJhu+OXQ5EX4xeppVRXPL5K5lGHInVlxkQXkVixSqn8rhqagolvLOzyvS0SFNjw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
